'use client';
import {useEffect,useState,useRef} from 'react';
import {ChefHat,ArrowRight,Clock,Users,ShoppingBasket,Check,UtensilsCrossed,MapPin,ExternalLink,BookOpen,ChevronLeft,ChevronRight,LoaderCircle,Leaf,Plus,PackageCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {INGREDIENTS,EQUIPMENT,EXCLUSIONS} from '@/lib/catalog.mjs';
import {parseInput,planMeals} from '@/lib/planner.mjs';
import {createRequestGate} from '@/lib/request-gate.mjs';

type Step={title:string;detail:string;minutes:number;recipe:string;start:number;end:number};
type Ingredient={id:string;name:string;unit:string;amount:number;available:number;shortage?:number};
type Recipe={id:string;name:string;note:string;ingredients:Record<string,number>};
type Meal={id:string;title:string;people:number;ingredients:Ingredient[];missing:Ingredient[];recipes:Recipe[];timeline:Step[];totalMinutes:number;cookingMinutes:number;shoppingMinutes:number;hasStaple:boolean};
type Draft={inventory:Record<string,number>;people:number|null;minutes:number|null;equipment:string[];exclusions:string[];unresolved:string[];mode:string|null};
type Store={id:string;name:string;address:string;walkMinutes:number;distanceMeters:number;url:string|null;open:boolean|null;attributions:{provider:string;providerUri:string|null}[]};
const examples=[{title:'冰箱裡的兩人晚餐',text:'雞蛋6顆、番茄300克、高麗菜300克、熟白飯400克、食用油40毫升、鹽5克、飲用水100毫升。兩個人，40分鐘，不吃辣，有平底鍋和爐火，只用現有食材。'},{title:'電鍋也能開飯',text:'雞蛋3顆、飲用水650毫升、鹽2克。一個人，35分鐘，有電鍋，只用現有食材。'},{title:'可以出門補一點',text:'板豆腐300克、鮮菇150克。兩個人，40分鐘，不吃蛋，有平底鍋和爐火，可以補買。'}];
function Choice({id,checked,onChange,children}:{id:string;checked:boolean;onChange:(v:boolean)=>void;children:React.ReactNode}){return <label className={'choice '+(checked?'chosen':'')} htmlFor={id}><Checkbox id={id} checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>}
export default function Home(){
 const parseGate=useRef(createRequestGate());const storeGate=useRef(createRequestGate());
 const [text,setText]=useState('');const [inventory,setInventory]=useState<Record<string,number>>({});
 const [people,setPeople]=useState(2);const [minutes,setMinutes]=useState(40);const [mode,setMode]=useState('strict');const [equipment,setEquipment]=useState<string[]>([]);const [exclusions,setExclusions]=useState<string[]>([]);
 const [unresolved,setUnresolved]=useState<string[]>([]);const [otherRestriction,setOtherRestriction]=useState('');const [parsed,setParsed]=useState(false);const [confirmed,setConfirmed]=useState(false);const [basics,setBasics]=useState(false);
 const [includeShopping,setIncludeShopping]=useState(false);const [shoppingMinutes,setShoppingMinutes]=useState(20);const [plans,setPlans]=useState<Meal[]>([]);const [selected,setSelected]=useState(0);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [capabilities,setCapabilities]=useState({ai:false,maps:false});const [useAI,setUseAI]=useState(false);
 const [location,setLocation]=useState('');const [walkMinutes,setWalkMinutes]=useState(10);const [storeBusy,setStoreBusy]=useState(false);const [stores,setStores]=useState<Store[]>([]);const [storeMessage,setStoreMessage]=useState('');const [resolvedLocation,setResolvedLocation]=useState('');const [stepOpen,setStepOpen]=useState(false);const [step,setStep]=useState(0);const [completed,setCompleted]=useState(false);
 useEffect(()=>{fetch('/api/status').then(r=>r.ok?r.json():null).then(v=>{if(v)setCapabilities(v)}).catch(()=>{});},[]);
 function invalidateStores(){storeGate.current.invalidate();setStoreBusy(false);setStores([]);setStoreMessage('');setResolvedLocation('');}
 function invalidate(){parseGate.current.invalidate();setBusy(false);invalidateStores();setPlans([]);setConfirmed(false);setMessage('');setStores([]);setStoreMessage('');setStepOpen(false);}
 function toggle(value:string,values:string[],set:(v:string[])=>void,on:boolean){invalidate();set(on?[...values,value]:values.filter(i=>i!==value));}
 function applyDraft(d:Draft){setInventory(d.inventory);setEquipment(d.equipment);setExclusions(d.exclusions);setUnresolved(d.unresolved);setOtherRestriction(d.unresolved.filter(s=>s.includes('忌口')).join('；'));if(d.people!==null)setPeople(d.people);if(d.minutes!==null)setMinutes(d.minutes);if(d.mode)setMode(d.mode);setParsed(true);setBasics(false);setMessage('已整理輸入。請確認下方的數量、忌口與廚具。');}
 async function parse(value=text){if(!value.trim()){setMessage('先告訴我手邊有哪些食材，或選一個範例。');return;}invalidate();const ticket=parseGate.current.begin();setBusy(true);try{if(useAI){const r=await fetch('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:value})});const d=await r.json();if(!parseGate.current.isCurrent(ticket))return;if(!r.ok||d.status!=='ok'){setMessage(d.message||'辨識未成功。');return;}applyDraft(d.draft);}else applyDraft(parseInput(value) as Draft);}catch{if(parseGate.current.isCurrent(ticket))setMessage('辨識暫時失敗，輸入仍保留，請重試。');}finally{if(parseGate.current.isCurrent(ticket))setBusy(false);}}
 function generate(){invalidateStores();if(otherRestriction.trim()){setMessage('仍有未確認的忌口。請將限制對應到下方項目；若無法對應，目前不能提供可靠推薦。');return;}if(!confirmed||!basics){setMessage('請確認食材清單與基本備料用品。');return;}const r=planMeals({inventory,people,minutes,equipment,exclusions,mode,shoppingMinutes:mode==='shop'&&includeShopping?shoppingMinutes:0});setPlans(r.plans as Meal[]);setSelected(0);setMessage(r.issues.join(' '));setStep(0);setCompleted(false);}
 async function lookup(){const ticket=storeGate.current.begin();setStoreBusy(true);setStores([]);setStoreMessage('');setResolvedLocation('');try{const r=await fetch('/api/stores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location,walkMinutes})});const d=await r.json();if(!storeGate.current.isCurrent(ticket))return;setStoreMessage(d.message||'');if(r.ok){setStores(d.stores||[]);setResolvedLocation(d.location||'');if(d.status==='ok'&&!d.stores?.length)setStoreMessage((d.message||'')+' 此範圍沒有可顯示的店家，可更換地標或增加步行時間。');}}catch{if(storeGate.current.isCurrent(ticket))setStoreMessage('目前無法查詢店家，請稍後再試或開啟地圖。');}finally{if(storeGate.current.isCurrent(ticket))setStoreBusy(false);}}
 const meal=plans[selected];const currentStep=meal?.timeline[step];
 return <div className="site-shell">
  <header className="topbar"><a className="brand" href="/" aria-label="今晚煮什麼首頁"><span className="brand-icon"><UtensilsCrossed size={22}/></span><span>今晚煮什麼<small>PANTRY TO TABLE</small></span></a><div className="top-links"><span className="beta">家庭料理實驗室 · BETA</span><a href="https://github.com/chevalier1216/pantry-to-table" target="_blank" rel="noreferrer">開源專案 <ExternalLink size={15}/></a></div></header>
  <main>
   <div className="page-heading"><div><p className="eyebrow">從冰箱，到餐桌</p><h1>今天，就用手邊的食材。</h1></div><p>告訴我有什麼，<br/>一起安排這一餐怎麼煮。</p></div>
   <div className="workspace">
    <section className="input-panel" aria-labelledby="input-heading">
     <div className="section-label"><span className="number">01</span><h2 id="input-heading">你的廚房，有些什麼？</h2></div>
     <label className="sr-only" htmlFor="request">食材、人數、忌口、廚具與料理時間</label>
     <textarea id="request" value={text} maxLength={3000} onChange={e=>{setText(e.target.value);setParsed(false);invalidate();}} placeholder="例如：雞蛋4顆、番茄300克，有平底鍋和爐火。兩個人吃，不吃辣，40分鐘內煮好。油、鹽和其他調味料也請告訴我。"/>
     <div className="input-meta"><span>食材數量越清楚，規劃越準確</span><span>{text.length} / 3000</span></div>
     <div className="example-list"><span>試試看</span>{examples.map(e=><button key={e.title} disabled={busy} onClick={()=>{setText(e.text);void parse(e.text)}}>{e.title}<ArrowRight size={13}/></button>)}</div>
     <div className="two-fields"><label><span><Users size={16}/>幾個人吃</span><div className="unit-input"><input aria-label="用餐人數" type="number" min={1} max={6} value={Number.isNaN(people)?'':people} onChange={e=>{invalidate();setPeople(e.target.valueAsNumber)}}/><b>人</b></div></label><label><span><Clock size={16}/>可用時間</span><div className="unit-input"><input aria-label="可用時間" type="number" min={1} max={240} value={Number.isNaN(minutes)?'':minutes} onChange={e=>{invalidate();setMinutes(e.target.valueAsNumber)}}/><b>分鐘</b></div></label></div>
     <label className="field-title">這次想怎麼準備？</label>
     <Tabs value={mode} onValueChange={v=>{invalidate();setMode(v)}}><TabsList className="mode-tabs"><TabsTrigger value="strict"><PackageCheck size={17}/>只用現有食材</TabsTrigger><TabsTrigger value="shop"><ShoppingBasket size={17}/>可以附近補買</TabsTrigger></TabsList></Tabs>
     <p className="small-note">{mode==='strict'?'油、鹽、水也會核對，不會偷偷加進食譜。':'優先用掉現有食材，缺少的材料另外列清單。'}</p>
     {mode==='shop'&&<div className="shopping-reserve"><Choice id="include-shopping" checked={includeShopping} onChange={v=>{invalidate();setIncludeShopping(v)}}>採買也算在可用時間內</Choice>{includeShopping&&<label className="inline-field">預留來回、選購與結帳<input aria-label="採買預留分鐘" type="number" min={1} max={120} value={Number.isNaN(shoppingMinutes)?'':shoppingMinutes} onChange={e=>{invalidate();setShoppingMinutes(e.target.valueAsNumber)}}/>分鐘</label>}</div>}
     <Button className="primary-action" onClick={()=>void parse()} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<ChefHat size={20}/>}整理我的料理條件<ArrowRight size={18}/></Button>
     <div className="parser-note">{capabilities.ai?<Choice id="use-ai" checked={useAI} onChange={v=>{setUseAI(v);setParsed(false);invalidate()}}>使用 AI 理解（輸入會傳至 OpenAI）</Choice>:<span>基本中文辨識 · 支援下方食材目錄，AI 尚未啟用</span>}</div>
    </section>
    <aside className="inspiration">
     <div className="food-photo"><img src="/family-dinner.png" alt="番茄炒蛋、高麗菜與白飯的家庭餐桌示意"/><span className="photo-tag"><Leaf size={14}/>家常菜，剛剛好</span><span className="image-caption">料理情境示意圖</span></div>
     <div className="inspiration-content"><p className="eyebrow">少一點猶豫，多一點開飯</p><h2>一餐的順序，<br/>也一起想好了。</h2><p>先備料、再開火，把每道菜排進同一份時間表。份量、缺料與每一步，煮之前都看得見。</p><div className="mini-features"><span><Check size={16}/>依人數換算</span><span><Check size={16}/>核對廚具</span><span><Check size={16}/>逐步教學</span></div></div>
    </aside>
   </div>
   <div className="status-message" role="status" aria-live="polite">{message}</div>
   {parsed&&<section className="confirmation" aria-labelledby="confirm-heading">
    <div className="section-label"><span className="number">02</span><h2 id="confirm-heading">開煮前，確認一下</h2><span className="section-aside">只會使用這裡確認的條件</span></div>
    {unresolved.length>0&&<div className="notice"><strong>有些內容需要你補充</strong><ul>{unresolved.map((s,i)=><li key={i}>{s}</li>)}</ul><p>請在下方補入可用數量。目錄以外的食材暫不使用；忌口不能忽略。</p></div>}
    <div className="confirm-grid"><div><h3>現有食材與調味料</h3><p className="small-note">留白表示沒有；蔬菜以重量計，不猜測半顆的大小。</p><div className="inventory-grid">{INGREDIENTS.map(i=><label className="inventory-item" key={i.id}><span>{i.name}</span><div><input aria-label={i.name+'現有'+i.unit} type="number" min={0} max={100000} step={i.id==='egg'?1:0.1} placeholder="沒有" value={inventory[i.id]??''} onChange={e=>{invalidate();const next={...inventory};if(e.target.value==='')delete next[i.id];else next[i.id]=e.target.valueAsNumber;setInventory(next)}}/><small>{i.unit}</small></div></label>)}</div></div>
    <div className="equipment-panel"><h3>可用廚具與熱源</h3><div className="choices">{EQUIPMENT.map(e=><Choice key={e.id} id={'tool-'+e.id} checked={equipment.includes(e.id)} onChange={v=>toggle(e.id,equipment,setEquipment,v)}>{e.name}</Choice>)}</div><Choice id="basics" checked={basics} onChange={v=>{setBasics(v);setConfirmed(false);setPlans([])}}>備妥刀、砧板、鍋鏟、碗盤及量具；用電鍋時也有蒸架、耐熱碗與隔熱手套</Choice>
     <h3>這餐必須避開</h3><p className="small-note">包含複合調味料。過敏者仍需核對產品標示及交叉接觸。</p><div className="choices">{EXCLUSIONS.map(e=><Choice key={e.id} id={'exclude-'+e.id} checked={exclusions.includes(e.id)} onChange={v=>toggle(e.id,exclusions,setExclusions,v)}>{e.name}</Choice>)}</div>
     {otherRestriction&&<label className="other-restriction">未確認的忌口（未解決前不能推薦）<input aria-label="未確認忌口" value={otherRestriction} onChange={e=>{invalidate();setOtherRestriction(e.target.value)}}/><span>請先選取上方對應限制，確認無遺漏後才清除此欄。</span></label>}
    </div></div>
    <div className="confirm-footer"><Choice id="confirmed" checked={confirmed} onChange={setConfirmed}>我已核對數量、人數、忌口和廚具，這次只依此清單規劃</Choice><Button className="generate" onClick={generate}>找出合適的餐點 <ArrowRight size={18}/></Button></div>
   </section>}
   {meal&&<section className="results" aria-labelledby="results-heading">
    <div className="section-label"><span className="number">03</span><h2 id="results-heading">這一餐，可以這樣煮</h2><span className="section-aside">{plans.length} 組符合條件 · 時間為估算</span></div>
    <div className="plan-options">{plans.map((p,i)=><button className={'plan-option '+(selected===i?'selected':'')} aria-pressed={selected===i} key={p.id} onClick={()=>{invalidateStores();setSelected(i);setStep(0);setCompleted(false);setStores([]);setStoreMessage('')}}><span className="option-label">{i===0?'優先推薦':'換個口味'}</span><strong>{p.title}</strong><span><Clock size={15}/>{p.totalMinutes} 分鐘 <span className="option-divider">·</span>{p.missing.length?`需補 ${p.missing.length} 種材料`:'材料都齊了'}</span></button>)}</div>
    <div className="meal-detail"><div className="meal-main"><div className="meal-title"><div><p className="eyebrow">你的料理安排</p><h2>{meal.title}</h2><p>{meal.people} 人份 · {meal.recipes.length} 道 · 料理約 {meal.cookingMinutes} 分鐘{meal.shoppingMinutes>0?` ＋ 採買預留 ${meal.shoppingMinutes} 分鐘`:''}</p></div><Button onClick={()=>{setStepOpen(true);setStep(0);setCompleted(false)}}><BookOpen size={17}/>逐步教學</Button></div>
     {!meal.hasStaple&&<p className="notice compact">這組是菜餚搭配，沒有主食；飯或麵若未列入，時間與份量也未包含。</p>}
     {mode==='shop'&&meal.missing.length>0&&!includeShopping&&<p className="small-note">目前時間不含採買；買齊材料後才能照此清單開始。</p>}
     <h3>整餐時間表</h3><p className="small-note">採依序烹調，已預留備料與整理；份量較大時會延長時間。</p>
     <ol className="timeline">{meal.shoppingMinutes>0&&<li><span className="timeline-time">0–{meal.shoppingMinutes}<small>分鐘</small></span><div><span className="timeline-dish">預留時間</span><h4>採買、往返與結帳</h4><p>由你設定的時間預留，不代表已確認店家有貨或來回路線。</p></div></li>}{meal.timeline.map((s,i)=><li key={i}><span className="timeline-time">{s.start}–{s.end}<small>分鐘</small></span><div><span className="timeline-dish">{s.recipe}</span><h4>{s.title}</h4><p>{s.detail}</p></div></li>)}</ol>
     {meal.recipes.map(r=><div className="recipe-reference" key={r.id}>{r.note&&<p className="small-note">{r.note}</p>}<a target="_blank" rel="noreferrer" href={'https://www.youtube.com/results?search_query='+encodeURIComponent(r.name+' 家常做法 教學')}>搜尋「{r.name}」影片教學 <ExternalLink size={14}/></a><small>外部搜尋結果，尚未核對；請以本頁的用量與限制為準。</small></div>)}
    </div><aside className="ingredients-summary"><h3><ShoppingBasket size={20}/>這一餐要用的材料</h3><p className="small-note">已合併每道菜的用量 · {meal.people} 人份</p><ul>{meal.ingredients.map(i=><li key={i.id}><span>{i.name}<small>現有 {i.available} {i.unit}</small></span><strong>{i.amount} {i.unit}</strong></li>)}</ul><div className={'stock-status '+(meal.missing.length?'shortage':'')}><strong>{meal.missing.length?'需要補買':'現有材料足夠'}</strong>{meal.missing.length?<ul>{meal.missing.map(i=><li key={i.id}><span>{i.name}</span><b>缺 {i.shortage} {i.unit}</b></li>)}</ul>:<p>不用為這份清單額外出門。</p>}</div>
    {meal.missing.length>0&&<div className="store-search"><h3><MapPin size={18}/>去哪裡補買？</h3><label>附近地標<input placeholder="例如：台北市大安站" value={location} maxLength={180} onChange={e=>{invalidateStores();setLocation(e.target.value);setStores([]);setStoreMessage('');setResolvedLocation('')}}/></label><label className="inline-field">單程步行上限<input aria-label="單程步行分鐘" type="number" min={1} max={30} value={Number.isNaN(walkMinutes)?'':walkMinutes} onChange={e=>{invalidateStores();setWalkMinutes(e.target.valueAsNumber);setStores([]);setStoreMessage('')}}/>分鐘</label><p className="small-note">查詢才會將地標傳給 Google，不需完整住址。</p><Button variant="outline" disabled={storeBusy||!location.trim()} onClick={()=>void lookup()}>{storeBusy?<LoaderCircle className="spin" size={16}/>:<MapPin size={16}/>}查詢步行可達店家</Button>{!capabilities.maps&&<p className="small-note">即時查詢尚未啟用，可先使用地圖搜尋。</p>}<p className="small-note" role="status">{storeMessage}</p>{resolvedLocation&&<p className="small-note">搜尋位置：{resolvedLocation}</p>}{stores.map(s=><article className="store" key={s.id}><h4>{s.name}</h4><p>步行約 {s.walkMinutes} 分鐘 · {s.distanceMeters} 公尺</p><p>{s.address}</p><p>{s.open===true?'資料顯示目前營業':s.open===false?'資料顯示目前未營業':'營業狀態未確認'} · 庫存未確認</p>{s.url&&<a href={s.url} target="_blank" rel="noreferrer">在 Google Maps 查看 <ExternalLink size={13}/></a>}{s.attributions?.map((a,i)=><small key={i}>{a.provider}</small>)}</article>)}{stores.length>0&&<p className="small-note">店家與路線資料：Google Maps。步行路線可能不完整，請留意實際道路狀況。</p>}{location.trim()&&<a className="map-link" target="_blank" rel="noreferrer" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(location+' 超市 生鮮 '+meal.missing.filter(i=>!['water','salt','oil'].includes(i.id)).map(i=>i.name).join(' '))}>自行開啟地圖搜尋 <ExternalLink size={14}/></a>}</div>}
    </aside></div>
   </section>}
   {!parsed&&<div className="catalog-note"><Plus size={17}/><p>第一版支援雞蛋、番茄、高麗菜、熟飯、豆腐、鮮菇與乾麵等食材。沒有適合的料理時，會直接告訴你。</p></div>}
  </main>
  <footer><span>Pantry to Table · 今晚煮什麼</span><span>原創食譜草案與示意圖 · 使用前確認食材狀態與產品標示</span><a href="https://github.com/chevalier1216/pantry-to-table" target="_blank" rel="noreferrer">MIT 開源</a></footer>
  <Dialog open={stepOpen} onOpenChange={setStepOpen}><DialogContent className="cook-dialog"><DialogHeader><DialogTitle>{completed?'這一餐，準備上桌。':currentStep?.recipe}</DialogTitle><DialogDescription>{completed?'請確認每道菜已熟透並關閉熱源。':`第 ${step+1} / ${meal?.timeline.length||0} 步 · 本步約 ${currentStep?.minutes||0} 分鐘`}</DialogDescription></DialogHeader>{completed?<div className="cook-complete"><Check size={36}/><p>時間表是估算，熟度與實際狀態更重要。</p><Button onClick={()=>setStepOpen(false)}>完成</Button></div>:currentStep&&<><div className="step-number">{String(step+1).padStart(2,'0')}</div><h2>{currentStep.title}</h2><p className="step-detail">{currentStep.detail}</p><div className="step-ingredients">{meal.recipes.filter(r=>r.name===currentStep.recipe).map(r=><p key={r.id}>本菜用量：{Object.entries(r.ingredients).map(([id,a])=>{const i=INGREDIENTS.find(i=>i.id===id)!;return `${i.name} ${a} ${i.unit}`}).join('、')}</p>)}</div><div className="step-controls"><Button variant="outline" disabled={step===0} onClick={()=>setStep(step-1)}><ChevronLeft size={16}/>上一步</Button><Button onClick={()=>{if(step===meal.timeline.length-1)setCompleted(true);else setStep(step+1)}}>{step===meal.timeline.length-1?'完成料理':'下一步'}<ChevronRight size={16}/></Button></div></>}</DialogContent></Dialog>
 </div>
}
